# docker-compose.yml
version: "3.8"
services:

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
    ports:
      - "8443:8443"
    volumes:
      - ./config:/config
      - ./certs:/config/certs   
